# Generated by Django 4.2.6 on 2024-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("ubicacion", models.CharField(max_length=255)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="torneos/"),
                ),
            ],
        ),
    ]
