# Generated by Django 4.2.21 on 2025-06-06 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImagenCarrusel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("imagen", models.ImageField(upload_to="carrusel_imagenes/")),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "orden",
                    models.IntegerField(
                        default=0, help_text="Define el orden en el carrusel"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Imágenes de Carrusel",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("todas_las_competencias", "Todas las competencias"),
                            ("Copa_America", "Copa América"),
                            ("Copa", "Copa"),
                            ("Liga", "Liga"),
                            ("Superliga", "Superliga"),
                            ("Desafio", "Desafío"),
                            ("Internacional", "Internacional"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha", models.DateField()),
                ("ubicacion", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("internacional", models.BooleanField(default=False)),
                (
                    "imagen_estatica",
                    models.CharField(
                        blank=True,
                        help_text="Ruta a la imagen estática del torneo (ej. 'images/nombre_torneo.png'). Debe estar en Torneos/static/images/",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Torneo Principal",
                "verbose_name_plural": "Torneos Principales",
            },
        ),
        migrations.CreateModel(
            name="InformacionTorneoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField()),
                ("campeon", models.CharField(max_length=100)),
                ("subcampeon", models.CharField(blank=True, max_length=100, null=True)),
                ("participantes_cantidad", models.IntegerField(blank=True, null=True)),
                ("resumen", models.TextField(blank=True, null=True)),
                (
                    "link_transmision",
                    models.URLField(
                        blank=True,
                        help_text="Enlace a la transmisión del torneo (Twitch, YouTube, etc.)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "fecha_exacta",
                    models.DateField(
                        blank=True,
                        help_text="Fecha específica de esta edición anual del torneo.",
                        null=True,
                    ),
                ),
                (
                    "ubicacion_especifica",
                    models.CharField(
                        blank=True,
                        help_text="Ubicación específica para esta edición anual.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "imagen_edicion_estatica",
                    models.CharField(
                        blank=True,
                        help_text="Ruta a la imagen estática de esta edición (ej. 'images/edicion_2023.png'). Debe estar en Torneos/static/images/",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informacion_por_anio",
                        to="Torneos.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Información de Torneo por Año",
                "ordering": ["-anio"],
                "unique_together": {("torneo", "anio")},
            },
        ),
    ]
