# Generated by Django 4.2.6 on 2024-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneo",
            name="internacional",
            field=models.BooleanField(default=False),
        ),
    ]
