# Generated by Django 4.2.21 on 2025-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagencarrusel",
            name="imagen",
        ),
        migrations.AddField(
            model_name="imagencarrusel",
            name="imagen_estatica",
            field=models.CharField(
                default=1,
                help_text="Ruta a la imagen estática del carrusel (ej. 'images/carrusel/imagen1.jpg'). Debe estar en Torneos/static/images/carrusel/",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
