# Generated by Django 4.2.21 on 2025-05-27 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Torneos", "0002_torneo_internacional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenCarrusel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título o pie de foto para la imagen del carrusel.",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("imagen", models.ImageField(upload_to="carrusel/")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Breve descripción o texto adicional para la imagen.",
                        null=True,
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Define el orden de aparición en el carrusel (menor número primero).",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Marca si la imagen debe mostrarse en el carrusel.",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora en que la imagen fue subida.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Carrusel",
                "verbose_name_plural": "Imágenes de Carrusel",
                "ordering": ["orden", "-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="InformacionTorneoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        help_text="Año al que se refiere esta información detallada (ej. 2023)."
                    ),
                ),
                (
                    "campeon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del campeón de ese año.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "subcampeon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del subcampeón de ese año.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "participantes_cantidad",
                    models.IntegerField(
                        blank=True,
                        help_text="Número de participantes en el torneo ese año.",
                        null=True,
                    ),
                ),
                (
                    "resumen",
                    models.TextField(
                        blank=True,
                        help_text="Un resumen de los eventos, momentos clave o resultados de ese año.",
                        null=True,
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        help_text="El torneo al que pertenece esta información anual.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_por_anio",
                        to="Torneos.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información por Año de Torneo",
                "verbose_name_plural": "Información por Año de Torneos",
                "ordering": ["-anio"],
                "unique_together": {("torneo", "anio")},
            },
        ),
    ]
