# Generated by Django 4.2.21 on 2025-06-09 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0002_remove_imagencarrusel_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagencarrusel',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Imágenes del Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='informaciontorneoanio',
            options={'ordering': ['-anio']},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={},
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen_estatica',
            field=models.CharField(help_text='Ruta a la imagen del carrusel (ej. images/carrusel/imagen1.png). Debe estar en torneos/static/images/carrusel/', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='titulo',
            field=models.CharField(default='Imagen de Carrusel', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informaciontorneoanio',
            name='campeon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='informaciontorneoanio',
            name='fecha_exacta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informaciontorneoanio',
            name='imagen_edicion_estatica',
            field=models.CharField(blank=True, help_text='Ruta a la imagen de la edición anual (ej. images/edicion_2023.png)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informaciontorneoanio',
            name='link_transmision',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informaciontorneoanio',
            name='subcampeon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='informaciontorneoanio',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='imagen_estatica',
            field=models.CharField(blank=True, help_text='Ruta a la imagen principal del torneo (ej. images/nombre_torneo.png). Debe estar en torneos/static/images/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ImagenAdicionalTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_estatica', models.CharField(help_text='Ruta a la imagen adicional (ej. images/galeria/torneo_foto1.png). Debe estar en torneos/static/images/galeria/', max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='Torneos.torneo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
