# Generated by Django 4.2.21 on 2025-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0003_alter_imagencarrusel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen_estatica',
            field=models.CharField(help_text='Ruta a la imagen estática del carrusel (ej. images/carrusel/imagen1.png). Debe estar en torneos/static/images/carrusel/', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
