# Generated by Django 4.2.21 on 2025-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0004_alter_imagencarrusel_imagen_estatica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='internacional',
        ),
        migrations.AddField(
            model_name='torneo',
            name='es_offline',
            field=models.BooleanField(default=False, help_text='Marca si el torneo es presencial/offline. Si no, se considera online.', verbose_name='¿Es offline (presencial)?'),
        ),
    ]
