# Generated by Django 4.2.21 on 2025-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneos", "0004_alter_imagencarrusel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informaciontorneoanio",
            options={
                "ordering": ["-anio"],
                "verbose_name_plural": "Información de Torneo por Año",
            },
        ),
        migrations.AlterModelOptions(
            name="torneo",
            options={
                "verbose_name": "Torneo Principal",
                "verbose_name_plural": "Torneos Principales",
            },
        ),
        migrations.AddField(
            model_name="informaciontorneoanio",
            name="fecha_exacta",
            field=models.DateField(
                blank=True,
                help_text="Fecha específica de esta edición anual del torneo.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informaciontorneoanio",
            name="link_transmision",
            field=models.URLField(
                blank=True,
                help_text="Enlace a la transmisión del torneo (Twitch, YouTube, etc.)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informaciontorneoanio",
            name="ubicacion_especifica",
            field=models.CharField(
                blank=True,
                help_text="Ubicación específica para esta edición anual.",
                max_length=100,
                null=True,
            ),
        ),
    ]
