# Generated by Django 4.2.21 on 2025-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneos", "0005_alter_informaciontorneoanio_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informaciontorneoanio",
            name="imagen_edicion",
            field=models.ImageField(
                blank=True,
                help_text="Imagen representativa de esta edición anual del torneo.",
                null=True,
                upload_to="ediciones_fotos/",
            ),
        ),
    ]
