# Generated by Django 4.2.21 on 2025-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneos", "0006_informaciontorneoanio_imagen_edicion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informaciontorneoanio",
            name="imagen_edicion",
        ),
        migrations.RemoveField(
            model_name="torneo",
            name="imagen_torneo",
        ),
        migrations.AddField(
            model_name="informaciontorneoanio",
            name="imagen_edicion_estatica",
            field=models.CharField(
                blank=True,
                help_text="Ruta a la imagen estática de esta edición (ej. 'images/edicion_2023.png'). Debe estar en Torneos/static/images/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="torneo",
            name="imagen_estatica",
            field=models.CharField(
                blank=True,
                help_text="Ruta a la imagen estática del torneo (ej. 'images/nombre_torneo.png'). Debe estar en Torneos/static/images/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="torneo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("todas_las_competencias", "Todas las competencias"),
                    ("Copa_America", "Copa América"),
                    ("Copa", "Copa"),
                    ("Liga", "Liga"),
                    ("Superliga", "Superliga"),
                    ("Desafio", "Desafío"),
                    ("Internacional", "Internacional"),
                ],
                max_length=50,
            ),
        ),
    ]
